# Generated by Django 3.0.7 on 2020-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200629_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='image',
            field=models.ImageField(default='null', upload_to='static/images'),
            preserve_default=False,
        ),
    ]
