# Generated by Django 3.0.7 on 2020-07-06 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_adduser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField(max_length=2000)),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 55, 59, 956229))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Adduser')),
            ],
        ),
    ]
